### ISSUE TITLE
Change name of object, Navigator list does not update

### ISSUE THREAD

**Issue by macMikey** [gcanyon/navigator#24]
I have a button.  It was called "button".  I changed the name in the property list in navigator, then hit "close", but the object list didn't update with the new name

**Comment by gcanyon** [comment]
Indeed, there are several places in Navigator where object name changes are made and don't trigger an update in Navigator. I'm looking at the update code now because updates get triggered too often, but I'll address this in the same effort.

That said, with the flexible display options in Navigator at this point, it's almost impossible to guarantee that the list stays up to date in all circumstances. For example, it would be easy to display an object's rect in Navigator's display, but it would be a monster headache to try to cause a list update in Navigator whenever an object's rect changes -- especially when it changes outside Navigator, say through dragging the control.

**Comment by gcanyon** [comment]
I realized what you were actually describing was simpler than I imagined. I added an update message to the Navigator property editor's update code, and I think this should be fixed now with 7.2.1
